package com.example.rentmanagement.utils

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream

/**
 * Generates a simple, professional single-page rent receipt PDF (spec section 11).
 * Uses android.graphics.pdf.PdfDocument directly — no third-party PDF library needed.
 */
object PdfReceiptGenerator {

    data class ReceiptData(
        val landlordName: String,
        val propertyName: String,
        val unitName: String,
        val tenantName: String,
        val amount: Double,
        val paymentDate: Long,
        val paymentMethod: String,
        val transactionId: String?,
        val billingMonth: String,
        val remainingBalance: Double,
        val receiptNumber: String,
        val currencySymbol: String
    )

    fun generate(context: Context, data: ReceiptData): File {
        val pageWidth = 595
        val pageHeight = 842
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 22f; isFakeBoldText = true; typeface = Typeface.DEFAULT_BOLD; color = Color.BLACK }
        val labelPaint = Paint().apply { textSize = 11f; color = Color.DKGRAY }
        val valuePaint = Paint().apply { textSize = 13f; color = Color.BLACK }
        val linePaint = Paint().apply { color = Color.LTGRAY; strokeWidth = 1f }
        val amountPaint = Paint().apply { textSize = 18f; isFakeBoldText = true; color = Color.BLACK }
        val footerPaint = Paint().apply { textSize = 10f; color = Color.GRAY }

        val left = 40f
        val labelX = left
        val valueX = 220f
        var y = 60f

        canvas.drawText("Rent Receipt", left, y, titlePaint)
        y += 10f
        canvas.drawLine(left, y, pageWidth - left, y, linePaint)
        y += 30f

        fun row(label: String, value: String) {
            canvas.drawText(label, labelX, y, labelPaint)
            canvas.drawText(value, valueX, y, valuePaint)
            y += 24f
        }

        row("Receipt No.", data.receiptNumber)
        row("Billing Month", data.billingMonth)
        row("Landlord", data.landlordName.ifBlank { "-" })
        row("Property", data.propertyName)
        row("Unit", data.unitName)
        row("Tenant", data.tenantName)
        row("Payment Date", DateUtils.formatDate(data.paymentDate))
        row("Payment Method", data.paymentMethod)
        if (!data.transactionId.isNullOrBlank()) {
            row("Transaction ID", data.transactionId)
        }

        y += 6f
        canvas.drawLine(left, y, pageWidth - left, y, linePaint)
        y += 30f

        canvas.drawText("Amount Paid", labelX, y, labelPaint)
        canvas.drawText(CurrencyFormatter.format(data.amount, data.currencySymbol), valueX, y, amountPaint)
        y += 28f
        canvas.drawText("Remaining Balance", labelX, y, labelPaint)
        canvas.drawText(CurrencyFormatter.format(data.remainingBalance, data.currencySymbol), valueX, y, valuePaint)

        canvas.drawText("Generated by Rent Manager", left, pageHeight - 40f, footerPaint)

        document.finishPage(page)

        val dir = File(context.filesDir, "receipts").apply { mkdirs() }
        val file = File(dir, "${data.receiptNumber}.pdf")
        FileOutputStream(file).use { document.writeTo(it) }
        document.close()
        return file
    }
}
